# Generated by Django 6.0.3 on 2026-03-06 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import habits.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HabitExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата выполнения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания записи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполнение привычки",
                "verbose_name_plural": "Выполнения привычек",
                "ordering": ["-execution_date"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Укажите место, в котором необходимо выполнять привычку.",
                        max_length=200,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Укажите время, когда необходимо выполнять привычку.",
                        null=True,
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Выберите действие, которое представляет собой привычка.",
                        max_length=500,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Признак приятной привычки - можно привязать к выполнению полезной привычки",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Вознаграждение"
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Укажите время в секундах, которое предположительно потратит пользователь на выполнение привычки (не более 120 секунд).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            habits.validators.validate_time_to_complete,
                        ],
                        verbose_name="Время выполнения (в секундах)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Публичная привычка"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Интервал между выполнениями привычки в днях (не более 7 дней).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            habits.validators.validate_periodicity,
                        ],
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная привычка (указывается для полезных привычек, не для приятных)",
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
