# Generated by Django 6.0.3 on 2026-03-16 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import habits.validators


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["-id"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False,
                help_text="Признак приятной привычки - можно привязать к выполнению полезной привычки.",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Признак публичности - можно сделать привычку публичной.",
                verbose_name="Публичная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Связанная привычка (указывается для полезных привычек, не для приятных).",
                limit_choices_to={"is_pleasant": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Добавьте вознаграждение за выполнение привычки (альтернатива связанной привычке).",
                max_length=200,
                verbose_name="Вознаграждение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=("Укажите время в секундах, которое предположительно потратит пользовательна выполнение",
                          "привычки (не более 120 секунд)."),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    habits.validators.validate_time_to_complete,
                ],
                verbose_name="Время выполнения (в секундах)",
            ),
        ),
    ]
