# Generated by Django 6.0.3 on 2026-03-16 17:13

import django.core.validators
import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_options_alter_habit_is_pleasant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.IntegerField(
                default=1,
                help_text="Интервал между выполнениями привычки в днях (не более 7 дней).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    habits.validators.validate_periodicity,
                ],
                verbose_name="Периодичность (в днях)",
            ),
        ),
    ]
